version: "3.7"
services:
  nginx:
    volumes:
      - ../docker-frontend/config/ssl:/etc/ssl:ro
      - ../docker-frontend/config/nginx/sites-dev:/etc/nginx/sites-enabled

  frontend:
    command: sh -c "yarn && yarn dev"  
    #command: sh -c "npm i && npm run dev"

  mailhog:
    container_name: mailhog_microjobs
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"